### PR TITLE
Accept boto3 rds data client as a connection arg to engine options

### PR DESCRIPTION
**Pull request by dnk8n**
I will continue testing out this idea tomorrow.

If you do have time to answer before than, do you think this would allow one to predefine a boto3 session and rds data client?

### CODE REVIEW

**Comment by dnk8n** [comment]
@kislyuk I found I needed this to use boto3 rds client to connect.

Change in action (this works as intended): https://gitlab.com/dnk8n/postgres-serverless-now/-/blob/master/api/index.py

**Comment by kislyuk** [comment]
Makes sense, thanks for contributing this.

**Comment by dnk8n** [comment]
It was my pleasure. Thank you for starting this project. Really helpful. I hope to use it in more complex examples and thereby give it some battle testing.

If serverless aurora could allow a minimum of 1 ACU and could cost half what it currently does, with half the cold start time (in case of paused DB), this would be such a compelling technology.

I am hopeful since recently they massively reduced the cost of Fargate by nearly 50%.

**Comment by vfan-platform** [comment]
@kislyuk Just wanted to let you know that there's a missing `)` on this merge:
https://github.com/chanzuckerberg/aurora-data-api/commit/a37ff71adea393c3002a47777622ce24364522e6#diff-fc5c5e4c065878e1216f22df192a3835R349

**Pull request merged**
